-- Drop old table if exists (we need to change schema drastically)
DROP TABLE IF EXISTS public.order_history;

-- Create generic order_history table
CREATE TABLE public.order_history (
    id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    order_id INT NOT NULL, -- RetailCRM ID
    
    -- Generic Event Data
    field_name TEXT NOT NULL, -- 'status', 'manager_comment', 'delivery', etc.
    old_value TEXT, -- JSON stringified if complex
    new_value TEXT, -- JSON stringified if complex
    
    manager_id INT, -- Who made the change (from 'user' field)
    created_at TIMESTAMPTZ NOT NULL, -- Event time
    source TEXT DEFAULT 'retailcrm',
    
    synced_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Constraint: One event per field per timestamp per order
    UNIQUE(order_id, field_name, created_at)
);

-- Enable RLS
ALTER TABLE public.order_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Allow public access" ON public.order_history FOR ALL USING (true) WITH CHECK (true);

-- Indexes
CREATE INDEX idx_order_history_order_id ON public.order_history(order_id);
CREATE INDEX idx_order_history_created_at ON public.order_history(created_at);
CREATE INDEX idx_order_history_field ON public.order_history(field_name);
