-- Create order_history table
CREATE TABLE IF NOT EXISTS order_history (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    crm_history_id bigint UNIQUE, -- ID from RetailCRM history
    order_id bigint NOT NULL,
    field text NOT NULL, -- 'status', 'manager', etc.
    old_value text,
    new_value text,
    event_time timestamptz NOT NULL, -- When the change happened
    manager_id text, -- Who made the change
    created_at timestamptz DEFAULT now()
);

-- Index for fast analysis
CREATE INDEX IF NOT EXISTS idx_order_history_order_id ON order_history(order_id);
CREATE INDEX IF NOT EXISTS idx_order_history_manager_id ON order_history(manager_id);
CREATE INDEX IF NOT EXISTS idx_order_history_event_time ON order_history(event_time);

-- Enable RLS
ALTER TABLE order_history ENABLE ROW LEVEL SECURITY;

-- Policies
CREATE POLICY "Allow public read" ON order_history FOR SELECT USING (true);
CREATE POLICY "Allow service_role full access" ON order_history USING (true) WITH CHECK (true);

-- Permissions
GRANT ALL ON order_history TO anon, authenticated, service_role;

NOTIFY pgrst, 'reload config';
