import postgres from 'postgres';
import { readFileSync } from 'fs';
const env = readFileSync('.env.local','utf8');
const url = env.match(/^DATABASE_URL=(.*)$/m)[1].trim().replace(/^["']|["']$/g,'');
const sql = postgres(url, { ssl: 'require' });
const ddl = readFileSync('migrations/20260630_email_order_blocklist.sql','utf8');
await sql.unsafe(ddl);
const cols = await sql.unsafe(`SELECT column_name, data_type, column_default FROM information_schema.columns WHERE table_name='email_intake_config' AND column_name='order_blocklist'`);
console.log('applied:', JSON.stringify(cols));
await sql.end();
